package view.animations;

/**
 * Created by 15852 on 2017/5/9 0009.
 */
public enum AnimatorSetting {
    ANIMATOR_SLIDEINLEFT,
    ANIMATOR_SLIDEINRIGHT,
    ANIMATOR_FADEIN,
    ANIMATOR_SLIDEINFROMUP,
    ANIMATOR_SLIDEINTODOWN,
    ANIMATOR_SLIDEFROMRIGHT,
    ANIMATOR_SLIDETORIGHT

}
